### PR TITLE
Check for color support whether printing colored sentences.

### PR DESCRIPTION
**Pull request by Plinio89s**
Check for color support whether printing colored sentences.

Also changed print functions name to match PIP8 pattern
(https://www.python.org/dev/peps/pep-0008/#function-names)

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
Thanks a lot @Plinio89s for letting me know this and for the PR :+1: :smile:

**Comment by Plinio89s** [comment]
My pleasure!
There's something wrong to the CI configuration. Are you aware and planned to fix that?

**Comment by gautamkrishnar** [comment]
@Plinio89s Yes i am still configuring it

**Comment by gautamkrishnar** [comment]
@Plinio89s i lost color on windows 10, Windows 10 supports colors:

### Before
screenshot 65

### After
screenshot 64


any idea on how to fix it?

**Comment by Plinio89s** [comment]
I noticed this side effect. I tried to find a solution but I couldn't, so I let the code exactly as it is in django. i.e. on windows terminal always shows without color. (Of course if this side effect bothers you, I won't be sad if you take the code away.) :)

**Comment by gautamkrishnar** [comment]
@Plinio89s  i think i can detect windows version and set it back... Thank you...

**Comment by gautamkrishnar** [comment]
Fixed that issue :smile: @Plinio89s

**Pull request merged**
