### PR TITLE
Contributing file 

### PR DESCRIPTION
**Pull request by akrish4**
#250  
Kindly do check and merge it @gautamkrishnar 
Kindly do add the labels also to issue and PR too

### CODE REVIEW

**Review by gautamkrishnar — APPROVED** [review]
LGTM

**Comment by gautamkrishnar** [comment]
@all-contributors please add @akrish4 for code

**Comment by gautamkrishnar** [comment]
@all-contributors please add @akrish4 for doc

**Comment by gautamkrishnar** [comment]
@all-contributors please add @akrish4 for doc

**Comment by divya-gh** [comment]
Hi, I'm new to open source projects. It would be a great pleasure to me if I would be able to contribute to this project. I love StackOverflow and I try to solve problems there as much as I can. Please guide me through and let me know how I can help.

**Comment by gautamkrishnar** [comment]
Sure @divya-gh please have a look at https://github.com/gautamkrishnar/socli/issues and let me know if you are interested in any of it.

**Pull request merged**
