### PR TITLE
Added c toggle to go to comments

### PR DESCRIPTION
**Pull request by ankushduacodes**
added c toggle to show comments and v to go back to answer

### CODE REVIEW

**Review by gautamkrishnar — CHANGES_REQUESTED** [review]
@ankushduacodes i can see a lots of formatting changes on this PR, which makes it harder to review. Can you plese reopen or update this with the changes required for the comment feature only, instead of refromattting all the python code. You can open a new PR for the formatting stuff.

**Comment by ankushduacodes** [comment]
> @ankushduacodes i can see a lots of formatting changes on this PR, which makes it harder to review. Can you plese reopen or update this with the changes required for the comment feature only, instead of refromattting all the python code. You can open a new PR for the formatting stuff.

- Sure i will revert some of pull reques

**Comment by gautamkrishnar** [comment]
You already dealt with the text formatting in https://github.com/gautamkrishnar/socli/pull/208, not sure why these changes are required!

**Comment by gautamkrishnar** [comment]
> * Sure i will revert some of pull requests

Feel free to close this one and reopen a new one if needed, with just the changes required for the comment feature after taking pull from the latest master branch.

**Comment by ankushduacodes** [comment]
I just hit format documents in vs code and it was done automatically. I usually do that in my documents, i will revert

**Comment by ankushduacodes** [comment]
> > * Sure i will revert some of pull requests
> 
> Feel free to close this one and reopen a new one if needed, with just the changes required for the comment feature after taking pull from the latest master branch.

Okay let me see..

**Pull request closed without merging**
