### PR TITLE
Fixing issue #195 dupl question display

### PR DESCRIPTION
**Pull request by suvhotta**
Commit addressing the issue #195

### CODE REVIEW

**Comment by suvhotta** [comment]
The previous commit had a few issues in passing the tests, hence adding a new commit to fix  #195 .

**Comment by suvhotta** [comment]
Hey @hedythedev  and @gautamkrishnar  I found a few errors in the pr that I've raised, can u please reject this one, meanwhile I can rectify the errors and resend the rectified version?

**Comment by hedythedev** [comment]
ok but you can actually close PRs yourself

**Comment by suvhotta** [comment]
ohh ok I didn't know that @hedythedev  thanks for the info. Bdw how do I test the changes before making a PR, any help here would be great!

**Comment by hedythedev** [comment]
well just run socli locally like `python -m socli <query>` after making changes

**Pull request closed without merging**
