### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by sk364**
This feature introduces the step into the `POST, PUT and DELETE` type of requests in StackOverflow which will require authentication of the user to perform the tasks, for eg -
* Asking / Editing a question
* Answering / Editing an answer
* Commenting on questions and/or answers
* Updating profile
* and, probably more ...

I have implemented the authentication system to use the `requests.Session` object to retrieve the cookies built in the session, which are saved for rebuilding the Session object to perform further tasks mentioned above such that user does not have to provide his/her credentials again and again.

Currently, I have saved the cookies in the `cwd`, which can be modified to be stored elsewhere (suggestions needed).

I have further created a `login_required` decorator method to ensure that the further tasks which are going to be implemented are proceeded only when the user is logged in.

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
Looking cool... Please let me know once it is complete... I will merge the pending PRs soon. Please update your code with that changes also...

**Comment by sk364** [comment]
It is completed with the `login` mechanism. I will add `logout` next.

**Comment by sk364** [comment]
Added logout. I think this is completed. We can add `Ask a Question` next in the CLI.

**Comment by gautamkrishnar** [comment]
@sk364 thanks for your contribution. Sorry for merging this lately.

**Pull request merged**
