### PR TITLE
made code base pep8 compliant and made some expressions pythonic

### PR DESCRIPTION
**Pull request by ankushduacodes**

### CODE REVIEW

**Review by hedythedev — APPROVED** [review]
Thanks, not sure if integrating [black](https://github.com/psf/black) or [flake8](https://flake8.pycqa.org/en/latest/) will be easier instead of fixing them manually @gautamkrishnar

**Comment by ankushduacodes** [comment]
> Thanks, not sure if integrating [black](https://github.com/psf/black) or [flake8](https://flake8.pycqa.org/en/latest/) will be easier instead of fixing them manually @gautamkrishnar

flake8 is much more rigorous than pep8, I think it require only 72 character per line instead pep8 allow about 120 character per line, I think it is possible to develop tests that will make sure every pull request follow that standard else it will produce conflicts.

**Comment by ankushduacodes** [comment]
> > Thanks, not sure if integrating [black](https://github.com/psf/black) or [flake8](https://flake8.pycqa.org/en/latest/) will be easier instead of fixing them manually @gautamkrishnar
> 
> @hedythedev flake8 is much more rigorous than pep8, I think it require only 72 character per line instead pep8 allow about 120 character per line, I think it is possible to develop tests that will make sure every pull request follow that standard else it will produce conflicts.

Easier thing would be to integrate autopep8

**Comment by gautamkrishnar** [comment]
@hedythedev please feel free to mege this if you are okay with the change. Regarding coding style enforcement, we can create a seprate issue.

**Comment by gautamkrishnar** [comment]
@all-contributors please add @ankushduacodes for code

**Pull request merged**
