### PR TITLE
Feature/make all text scrollable

### PR DESCRIPTION
**Pull request by aaxu**
I adjusted the QuestionPage class so that now the question and answer each take about half the terminal. There was a problem before where if the question had too many lines, the user would not be able to view the answer when in Interactive mode. This implementation resolves this issue. In addition, the amount of space question and answer takes up also adjusts if the user resizes the terminal. I had to move several classes and variables defined in **socli_interactive** to the global environment in order to make it accessible to the other functions as well.

I also made regular search, tag search, and manual search look like how questions are displayed when you are in interactive mode. This allows the text to not be cut off mid word and also provides all the answers for that question, not just the top one.

Note: This change does not apply to Windows since that uses another set of logic. Will need to implement some new type of interface to display text for Windows in the future.

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
Thanks a lot @aaxu. I think @e-beach will be the best person to review this.

**Comment by aaxu** [comment]
@gautamkrishnar Do you know why the checks seems to have failed? I can't seem to figure out the error. There are no merge conflicts and it's been working fine.

**Comment by gautamkrishnar** [comment]
@aaxu just ignore the tests. I will fix it soon...

**Comment by aaxu** [comment]
Oh alright @gautamkrishnar. Thanks a lot!

**Comment by aaxu** [comment]
What are people's thoughts on a pager module like **less** to display instead of the format seen in interactive mode? I think this format I implemented is more UI friendly, but **less** may be better for more advanced users because it provides functions and other shortcut keys. If we use a paging module, we would also have to make words somehow be printed better so that they don't break line midword to make it more readable.

**Comment by gautamkrishnar** [comment]
@aaxu yes i think using interactive mode is better...

**Comment by gautamkrishnar** [comment]
@e-beach requesting your review...

**Pull request merged**
