### PR TITLE
Added json-output flag

### PR DESCRIPTION
**Pull request by ssiyad**
- Add `--json-output` flag

Sorry for linting whole files, really don't know how to turn it off :/

### CODE REVIEW

**Comment by ssiyad** [comment]
Most probably closes #232

**Comment by gautamkrishnar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
- Added 4
           

Complexity increasing per file
==============================
- socli/socli.py  1
         

Clones removed
==============
+ socli/socli.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gautamkrishnar/socli/pullRequest?prid=6294638&bid=20476573)

**Review by gautamkrishnar — CHANGES_REQUESTED** [review]
@ssiyad please don't reformat the entire source code using the IDE, It is harder to review. Can you please revert the formatting changes?

**Comment by ssiyad** [comment]
@gautamkrishnar Can you have a look please?

**Comment by gautamkrishnar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- socli/socli.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gautamkrishnar/socli/pullRequest?prid=6294638&bid=20476573)

**Review by gautamkrishnar — CHANGES_REQUESTED** [review]
hi @ssiyad thanks for updating, Btw this is not what it meant in the ticket #232, raw output means simply outputting the question and answer to the terminal, not converting it to JSON.
Eg:
```
socli --raw-output for loop python | grep for
```

But this feature is good to have, can you rename the flag to `--json` instead of --raw-output. I will take a look once it is done.

**Comment by ssiyad** [comment]
@gautamkrishnar done

**Comment by gautamkrishnar** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- socli/socli.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gautamkrishnar/socli/pullRequest?prid=6294638&bid=20476573)

**Comment by gautamkrishnar** [comment]
@all-contributors please add @ssiyad for code

**Comment by gautamkrishnar** [comment]
@ssiyad thanks a lot for contributing....

**Comment by ssiyad** [comment]
Thank you @gautamkrishnar ! <3

**Pull request merged**
