### PR TITLE
remove  and import json within top of socli.py

### PR DESCRIPTION
**Pull request by arount**
Remove `import_json` function and prefere to simply import json in top of `socli.py`

## Questions

+ Why was it done like it ? (if is there a real reason)
+ Is pushing on develop ok ? or do you prefere master ?
+ Some lines are updated .. I don't really understand why, I checked spaces / tabs and stuff like that but I can not figure what's going on with these lines ..

### CODE REVIEW

**Comment by arount** [comment]
I close this, I will be back quickly with way more diffs, sry ^^

**Comment by arount** [comment]
well, i need info about master vs develop before.
Tell me which one I should update.
thx

**Comment by gautamkrishnar** [comment]
I imported that lately because it is need only for user profile.... It may improve perfomance...

**Comment by gautamkrishnar** [comment]
Thanks for correcting me Buddy... We can reopen this pr

**Comment by arount** [comment]
ty!

**Pull request merged**
