### PR TITLE
Regex needs to be changed slightly.

### PR DESCRIPTION
**Pull request by therajdeepbiswas**
File `socli/search.py`, line number `398` had the following regex: `r"/questions/[0-9]+"`. However this causes some URLs that contain `'Question'` (with an uppercase) to return a `None` type that results in the question being omitted entirely from the search results.

On printing `(i, question_url)` before and after the `fix_google_url()` call on line `90`. (excuse my terrible methods of debugging)
image

I am new to regexes, hence, I'm not sure if the change I made is absolutely correct. Please suggest me the correct change and point of **note**: please check if this change also results in different search results being returned (the order of the results or even completely different results).

### CODE REVIEW

**Comment by therajdeepbiswas** [comment]
@hedythedev, requesting review.

**Comment by hedythedev** [comment]
I think you could use `re.IGNORECASE` instead

**Comment by therajdeepbiswas** [comment]
@hedythedev please merge if this is approved.

**Comment by therajdeepbiswas** [comment]
Closing PR. Considering I'll `.lower()` URLs before regexing them as a part of my work on #183

**Comment by therajdeepbiswas** [comment]
We might want to make this change to not miss out on some questions, which we at the moment are. @gautamkrishnar. I have done a `lower()` implementation which I believe will be less expensive than adding an `.IGNORECASE` to the regex.

**Comment by hedythedev** [comment]
@gautamkrishnar accept changes?

**Comment by gautamkrishnar** [comment]
@hedythedev LGTM 👍

**Comment by gautamkrishnar** [comment]
@hedythedev feel free to trigger a release if you want with these changes. Please make sure that you update the https://github.com/gautamkrishnar/socli/blob/master/CHANGELOG.rst and version in https://github.com/gautamkrishnar/socli/blob/master/setup.py, Once you have those changes committed to master, you can trigger a build.

**Comment by gautamkrishnar** [comment]
@therajdeepbiswas as a small reward please accept $14.00 in your issue hunt account https://issuehunt.io/repos/61608885/issues/149 for your contributions.

**Comment by therajdeepbiswas** [comment]
Thank you for this gesture @gautamkrishnar!

**Pull request merged**
