### PR TITLE
Issue179

### PR DESCRIPTION
**Pull request by adamjyz**
This is a solution on the issue #179 and maybe an improvement on #180 . The initial solution provided by @therajdeepbiswas was great, but it heavily relies on the css tag. The changes I've made ensures that we first locate the information by finding the "time" tag, and then we traverse back to its parent to find all the necessary information of asked_info, active_info and viewed_info. The code is relatively straight forward to understand, as all those three information can be achieved by access the 'div' and we can even use the words from StackOverflow directly so that we don't need to hand code things like 'asked ...', 'active ...' and 'viewed ...' 

This is my very first attempt on contributing on an open source project, and I've found socli a great project to work on. Please note that I forked it when it was version 4.0 I believe, but search.py is the only file I've changed. Please review the pull request and let me know if this is a good solution that can be merged into the master branch or if you have any other feedback. Thank you.

Screen Shot 2020-06-25 at 8 09 36 AM

### CODE REVIEW

**Comment by hedythedev** [comment]
Thanks for submitting your first pr, this is definitely easier to understand than the previous solution. I will test this later.

Also, I'm not quite sure whether the `except IndexError` would be suitable in this case, but I might be wrong

**Comment by hedythedev** [comment]
ok, I tested your changes locally and it is working fine. I suggest that on line 141 of search.py we should change `except IndexError` to just `except` because there is no indexing like `[0]` anymore.

**Comment by adamjyz** [comment]
I definitely agree with you. I should have taken a look at the line 141 before pushing it, and I think having except should be enough in this case. I've made the change and tried to push it, but it seems like I'm failing to do so. Any tips on how to make it work? Sorry for not being familiar with the process as I'm fairly new to the community.

Screen Shot 2020-06-26 at 12 08 19 AM

**Comment by hedythedev** [comment]
It seams that something has changed on remote before you tried to push. You could do a pull before that but there may be merge conflicts to resolve. What you can do is just edit it on GitHub. So go to this pr page, click ‘files changed’ tab, then, click on the three dots on the right, select ‘edit file’, and make the changes there.

**Comment by adamjyz** [comment]
Thanks for the quick instruction, that's really helpful. I've made the change successfully.

**Comment by hedythedev** [comment]
@gautamkrishnar requesting review

**Comment by gautamkrishnar** [comment]
@adamjyz can you please resolve the conflicts

**Comment by hedythedev** [comment]
@adamjyz I will resolve it for you

**Comment by adamjyz** [comment]
Sorry for not being able to respond to the request as I have been extremely busy on other things all day today... @hedythedev 
 Thank you Hedy for helping me out. Please let me know if there's still anything I need to do right now.

**Comment by hedythedev** [comment]
@all-contributors please add @adamjyz for code

**Pull request merged**
