### PR TITLE
Fixed special char display problem

### PR DESCRIPTION
**Pull request by aharshac**
Fixes: #22

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@aharshac Thank you for your contribution.  I will review this one once I reach my home.

**Comment by gautamkrishnar** [comment]
We need to display the single quotes and double quotes in the  question title... Will it be replaced by this regex?

**Comment by aharshac** [comment]
@gautamkrishnar, no I haven't fixed that because I didn't know your exact requirements at that time. Please send them to me.

**Comment by gautamkrishnar** [comment]
We need to display the double quotes and single quotes in the question title.  Please modify the regular expression to ignore that too... Also all the common punctuators and separators used in programming languages.

**Comment by aharshac** [comment]
Please read the thread in Collaborizm. I've explained a possible fix there.

**Comment by gautamkrishnar** [comment]
@aharshac okay let me check!

**Comment by gautamkrishnar** [comment]
@aharshac I saw your reply on collaborizm, can you fix it yourself?
Here's a reference link: http://stackoverflow.com/questions/3592673/change-console-font-in-windows

**Comment by aharshac** [comment]
Ok. I'll push by tonight.

**Comment by gautamkrishnar** [comment]
Thank you for your contribution. I had made some updates to execute the `chcp` command as well. 😄  Now the bug is almost fixed...

**Pull request merged**
