### PR TITLE
ignore *.pyc & refactored for better readability

### PR DESCRIPTION
**Pull request by nagracks**
should ignore *.pyc

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
Lopk

**Comment by nagracks** [comment]
I can do that

**Comment by gautamkrishnar** [comment]
Thanks :smile: waiting...  :dance:

**Comment by nagracks** [comment]
On Thu, Jun 30, 2016 at 12:37:30PM -0700, Gautam krishna.R wrote:
>Thanks 😄 waiting... :dance:
>
>—
>You are receiving this because you were mentioned.
>Reply to this email directly, view it on GitHub, or mute the thread.*
>
done

**Comment by nagracks** [comment]
done

**Pull request closed without merging**
