### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by tarbz2**
We make the translation structure files based on the gettext (used in i18n), and the first translation (es_AR).

### CODE REVIEW

**Comment by patricio87209** [comment]
Looking forward for your review!

**Comment by gautamkrishnar** [comment]
@tarbz2 can you please fix the conflicts.

**Comment by patricio87209** [comment]
I believe we deleted a help line by accident, we will look into it during the week. The one that reads "Opens the documentation of Python2 and Python3 and let you navigate through".

**Comment by patricio87209** [comment]
@gautamkrishnar conflict fixed :wrench: , we added the translation to the new doc feature. Hope you like it!

**Comment by patricio87209** [comment]
@tarbz2 commited the markdown changes to the guide. Also added a link to the guide in the readme file, but that link wont work until the guide is on the master branch.

**Comment by gautamkrishnar** [comment]
@tarbz2 Can you please rebase it with the latest version of the code if you are free...

**Comment by gautamkrishnar** [comment]
Closing this since this is stale

**Comment by tarbz2** [comment]
@gautamkrishnar OK. I'm sorry, it's impossible for me to check the pull request.

**Comment by gautamkrishnar** [comment]
@tarbz2 it's okay, thanks a lot for your effort. Please feel free to reopen this anytime in the future when you have time.

**Pull request closed without merging**
