### PR TITLE
Display a correct message when statistics could not be loaded.

### PR DESCRIPTION
**Pull request by aaxu**
Print seem to print the message, so I set question_stats to the desired error message.

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@aaxu please allow me to edit your repo so that i can make some changes before merging this pr:
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by gautamkrishnar** [comment]
@aaxu good find ⭐️ Thanks again!

**Comment by aaxu** [comment]
Sorry @gautamkrishnar, I thought I have always been checking the "Allow maintainer to make changes to PR." Didn't notice that I had to check the box on the right. I don't know all the conventions for Open Source yet so thank you for being lenient! I'll be sure to make all future PRs to develop branch too.

Just a quick question for clarification (not sure where I'm supposed to post this) : Suppose I make a PR to merge a bugfix into develop (where develop contains buggy features that you don't want in the master). How would you apply the bugfix to master without merging all of the develop branch's experimental features?

**Comment by gautamkrishnar** [comment]
Its okay 😄. Git is confusing when you use it for first time, especially for open source contributions 👍 . Its entirely different from working on your own project. I recommend you to watch this video: https://www.youtube.com/watch?v=oFYyTZwMyAg


Different projects follow different workflows. I prefer git branch workflow that uses **develop** branch for pull requests. The best way to fix something is just creating a new branch from the master and then trying to merge the current version of the develop. It will work fine since **develop** is also a branch created from master, Then you can simply make modifications, commit the changes and submit the PR to the projects **develop** branch. Once we had fixed all the bugs and completed implementing some features we will merge **develop** with **master** and deploy the master branch to all of our users. So that we can keep our master clean from unfinished works.

**Comment by aaxu** [comment]
Oh okay thanks! Is it typical to ask for the maintainer's workflow when you start working on someone else's project? Also, what if it's like the README changes or the simple bug fix where I added 8 as a valid key in QuestionPage, or just a hotfix? Do you still want them to go under the **develop** branch? Doesn't that mean these fixes won't be applied until whatever's in **develop** has been finished testing and can be deployed?

**Comment by gautamkrishnar** [comment]
@aaxu yes for convenience i would like to see the minor fixes in the development branch. For minor changes its okay to use master, it wont make any difference. Github suggest you to keep the master branch clean even fro minor changes while working.

Yes its better ask the maintainer about the workflow. Most projects contain that in its README.md or CONTRIBUTING.md Please check these files before opening a PR.

**Comment by aaxu** [comment]
Okay! :+1: Thanks for helping me out. Planning on implementing a few features so expect more PRs soon!

**Comment by gautamkrishnar** [comment]
Thanks a lot @aaxu you rocks! 🥇 . Please remember to work with the uptodate version of the project. Its better to fork it again after deleting it to remove all your previous commits.

**Comment by aaxu** [comment]
Is it okay to just delete my local branch and pull your develop / master branches to update my own develop / master branches? I read that deleting the forked repo has some buggy effects on your contributions so I don't want to delete them. Since i'm only committing on my local branches, this should keep my commit history pretty clean I think. I just need to only perform upstream pulls from master and develop.

**Comment by aaxu** [comment]
Although I'll need to refork now since I already messed up the commit history of those two branches haha

**Comment by gautamkrishnar** [comment]
@aaxu their is no problem with deleting your fork since all your pull requests are merged...

**Pull request merged**
